[versions]
kotlin = "2.2.21"
kotlinx-benchmark = "0.4.14"
ktlint = "14.0.1"
inputs-downloader = "0.0.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
aoc-inputs-downloader = { id = "com.shykial.aoc.inputs.downloader", version.ref = "inputs-downloader" }

[libraries]
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }
